const medicineDB = [
  {
    name: "Medicine 1",
    genricName: "Medicene 1 Gen Name",
    disease: "Disease 1",
    price: "250",
    manufacturer: "Manufacturer 1",
    isPrescription: false,
  },
  {
    name: "Medicine 2",
    genricName: "Medicene 2 Gen Name",
    disease: "Disease 2",
    price: "800",
    manufacturer: "Manufacturer 2",
    isPrescription: true,
  },
  {
    name: "Medicine 3",
    genricName: "Medicene 3 Gen Name",
    disease: "Disease 3",
    price: "750",
    manufacturer: "Manufacturer 3",
    isPrescription: false,
  },
  {
    name: "Medicine 4",
    genricName: "Medicene 4 Gen Name",
    disease: "Disease 4",
    price: "650",
    manufacturer: "Manufacturer 4",
    isPrescription: true,
  },
  {
    name: "Medicine 5",
    genricName: "Medicene 5 Gen Name",
    disease: "Disease 5",
    price: "500",
    manufacturer: "Manufacturer 5",
    isPrescription: true,
  },
  {
    name: "Medicine 6",
    genricName: "Medicene 6 Gen Name",
    disease: "Disease 6",
    price: "450",
    manufacturer: "Manufacturer 6",
    isPrescription: false,
  },
  {
    name: "Medicine 7",
    genricName: "Medicene 7 Gen Name",
    disease: "Disease 7",
    price: "350",
    manufacturer: "Manufacturer 7",
    isPrescription: true,
  },
  {
    name: "Medicine 8",
    genricName: "Medicene 8 Gen Name",
    disease: "Disease 8",
    price: "2250",
    manufacturer: "Manufacturer 8",
    isPrescription: false,
  },
  {
    name: "Medicine 9",
    genricName: "Medicene 9 Gen Name",
    disease: "Disease 9",
    price: "1250",
    manufacturer: "Manufacturer 9",
    isPrescription: false,
  },
  {
    name: "Medicine 10",
    genricName: "Medicene 10 Gen Name",
    disease: "Disease 10",
    price: "1000",
    manufacturer: "Manufacturer 10",
    isPrescription: true,
  },
];

export default medicineDB;
